default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: desafio_back_end_development

test:
  <<: *default
  database: desafio_back_end_test
  
production:
  <<: *default
  database: desafio_back_end_production
  username: desafio_back_end
  password: <%= ENV['DESAFIO_BACK_END_DATABASE_PASSWORD'] %>

